/**
 * F-COM-002 화면을 실제 API 연결 전에 확인하기 위한 가명 자료입니다.
 * 다른 담당자의 DB 식별자나 개인정보를 복사하지 않았으며, API가 오면 이 파일은 제거할 수 있습니다.
 */
// 담당자 7: CATEGORY의 현재 서비스 분류(이사·청소·레슨·설치·수리·인테리어)와 같은 이름을 사용합니다.
export const SERVICE_CATEGORIES = ['이사', '청소', '레슨', '설치·수리', '인테리어'];

export const SERVICE_REGIONS = ['서울', '경기', '인천', '부산', '경남', '비대면'];

export const SERVICE_REQUEST_PREVIEW = [
  {
    id: 101,
    title: '원룸 입주 청소를 부탁드려요',
    category: '청소',
    region: '서울',
    budgetMin: 120000,
    budgetMax: 180000,
    budgetLabel: '120,000~180,000원',
    status: '견적 모집중',
    deadlineOrder: 1,
    quoteCount: 2,
    createdOrder: 8,
    remote: false,
    summary: '욕실·주방과 창틀까지 포함한 입주 전 전체 청소 요청입니다.',
  },
  {
    id: 102,
    title: '소형 이사와 가구 재배치가 필요해요',
    category: '이사',
    region: '경기·인천',
    budgetMin: 150000,
    budgetMax: 150000,
    budgetLabel: '150,000원',
    status: '마감임박',
    deadlineOrder: 0,
    quoteCount: 4,
    createdOrder: 6,
    remote: false,
    summary: '엘리베이터가 있는 오피스텔에서 차량 1대로 이동하는 일정입니다.',
  },
  {
    id: 103,
    title: '거실 부분 인테리어 상담',
    category: '인테리어',
    region: '서울',
    budgetMin: 70000,
    budgetMax: 70000,
    budgetLabel: '70,000원',
    status: '견적 0건',
    deadlineOrder: 2,
    quoteCount: 0,
    createdOrder: 7,
    remote: false,
    summary: '거실 벽면과 조명 교체 범위를 먼저 상담받고 싶습니다.',
  },
  {
    id: 104,
    title: '주 2회 온라인 영어 회화 레슨',
    category: '레슨',
    region: '비대면',
    budgetMin: 350000,
    budgetMax: 400000,
    budgetLabel: '월 350,000~400,000원',
    status: '견적 모집중',
    deadlineOrder: 5,
    quoteCount: 3,
    createdOrder: 5,
    remote: true,
    summary: '평일 저녁 화상 수업으로 업무 영어 회화를 연습하고 싶습니다.',
  },
  {
    id: 105,
    title: '세탁기 배수 호스 점검 요청',
    category: '설치·수리',
    region: '부산·경남',
    budgetMin: 45000,
    budgetMax: 80000,
    budgetLabel: '45,000~80,000원',
    status: '견적 모집중',
    deadlineOrder: 3,
    quoteCount: 1,
    createdOrder: 4,
    remote: false,
    summary: '세탁 후 배수 부근에 물이 고여 호스와 연결부 점검이 필요합니다.',
  },
  {
    id: 106,
    title: '이력서와 포트폴리오 피드백',
    category: '레슨',
    region: '비대면',
    budgetMin: 50000,
    budgetMax: 100000,
    budgetLabel: '회당 50,000~100,000원',
    status: '견적 0건',
    deadlineOrder: 4,
    quoteCount: 0,
    createdOrder: 3,
    remote: true,
    summary: '디자인 직군 지원용 자료의 구성과 문장 피드백을 받고 싶습니다.',
  },
];

export const PROVIDER_PREVIEW = [
  {
    id: 201,
    ownerUserId: 9201,
    name: '청년이사',
    verified: true,
    rating: 4.7,
    reviewCount: 23,
    completedCount: 18,
    responseRate: 94,
    categories: ['청소', '이사'],
    regions: ['서울', '경기·인천'],
    minBudget: 90000,
    intro: '소형 이사와 입주 청소를 함께 진행합니다. 사전 체크리스트로 추가 비용을 투명하게 안내합니다.',
    reviews: [
      { id: 1, score: 5, author: '김**', date: '2026-06-12', content: '시간 약속을 잘 지켰고 포장이 꼼꼼했습니다.' },
      { id: 2, score: 4, author: '이**', date: '2026-06-08', content: '응답이 빠르고 추가 비용 설명이 명확했습니다.' },
      { id: 3, score: 5, author: '박**', date: '2026-06-03', content: '청소까지 마무리해 주셔서 만족했습니다.' },
    ],
    portfolios: [
      { id: 1, title: '소형 이사·입주 청소', category: '이사', description: '원룸 이사 후 바로 입주할 수 있도록 운반과 기본 청소를 같은 일정에 진행했습니다.' },
      { id: 2, title: '원룸 포장 이사', category: '이사', description: '가전과 생활용품을 구역별로 분류해 포장하고 파손 없이 운반한 사례입니다.' },
      { id: 3, title: '가구 재배치', category: '설치·수리', description: '대형 가구 이동 동선을 확보하고 벽면 손상 없이 재배치했습니다.' },
      { id: 4, title: '퇴실 청소', category: '청소', description: '욕실, 주방, 창틀 등 오염 구역 중심으로 마감한 청소 사례입니다.' },
    ],
  },
  {
    id: 202,
    ownerUserId: 9202,
    name: '바른홈케어',
    verified: true,
    rating: 4.9,
    reviewCount: 41,
    completedCount: 37,
    responseRate: 97,
    categories: ['청소', '설치·수리'],
    regions: ['서울', '경기·인천'],
    minBudget: 60000,
    intro: '생활 공간 청소와 간단한 설치 작업을 한 번에 상담합니다.',
    reviews: [],
    portfolios: [],
  },
  {
    id: 203,
    ownerUserId: 9203,
    name: '온택트커리어',
    verified: true,
    rating: 4.8,
    reviewCount: 16,
    completedCount: 14,
    responseRate: 91,
    categories: ['레슨'],
    regions: ['비대면'],
    minBudget: 50000,
    intro: '취업 문서와 면접을 비대면으로 함께 점검합니다.',
    reviews: [],
    portfolios: [],
  },
  {
    id: 204,
    ownerUserId: 9204,
    name: '부산생활수리',
    verified: true,
    rating: 4.6,
    reviewCount: 12,
    completedCount: 21,
    responseRate: 89,
    categories: ['설치·수리'],
    regions: ['부산·경남'],
    minBudget: 40000,
    intro: '수전, 배수, 선반 등 일상에서 자주 필요한 소형 수리를 진행합니다.',
    reviews: [],
    portfolios: [],
  },
];

export const PROVIDER_REPORT_TYPES = [
  { code: 'ABRC0001', name: '콘텐츠' },
  { code: 'ABRC0002', name: '사용자' },
  { code: 'ABRC0003', name: '스팸·광고' },
  { code: 'ABRC0004', name: '기타' },
];
